<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $players = [
            [
                'number'  => 13,
                'name'    => 'Manu Moreno',
                'role'    => 'Portero',
                'photo'   => 'manu-moreno.jpg',
                'minutes' => 60,
                'goals'   => 0,
                'matches' => 1,
            ],
            [
                'number'  => 31,
                'name'    => 'Adrián',
                'role'    => 'Defensa',
                'photo'   => 'adrian.jpg',
                'minutes' => 45,
                'goals'   => 0,
                'matches' => 1,
            ],
                        [
                'number'  => 14,
                'name'    => 'Rafa',
                'role'    => 'Defensa',
                'photo'   => 'rafa.jpg',
                'minutes' => 50,
                'goals'   => 0,
                'matches' => 1,
            ],
            [
                'number'  => 99,
                'name'    => 'Álex (Castolo)',
                'role'    => 'Lateral',
                'photo'   => 'alex.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 10,
                'name'    => 'Gonzalo',
                'role'    => 'Lateral',
                'photo'   => 'gonzalo.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 33,
                'name'    => 'Dani',
                'role'    => 'Defensa',
                'photo'   => 'dani.jpg',
                'minutes' => 30,
                'goals'   => 0,
                'matches' => 1,
            ],
            [
                'number'  => 22,
                'name'    => 'Manu',
                'role'    => 'Lateral',
                'photo'   => 'manu.jpg',
                'minutes' => 10,
                'goals'   => 0,
                'matches' => 1,
            ],
                        [
                'number'  => 4,
                'name'    => 'Alberto',
                'role'    => 'Defensa',
                'photo'   => 'alberto.jpg',
                'minutes' => 20,
                'goals'   => 0,
                'matches' => 1,
            ],
            [
                'number'  => 3,
                'name'    => 'Charlie',
                'role'    => 'Defensa',
                'photo'   => 'charlie.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 2,
                'name'    => 'Marcos',
                'role'    => 'Defensa',
                'photo'   => 'marcos.jpg',
                'minutes' => 30,
                'goals'   => 1,
                'matches' => 1,
            ],
            [
                'number'  => 8,
                'name'    => 'Chechu',
                'role'    => 'Lateral',
                'photo'   => 'chechu.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 6,
                'name'    => 'Unai',
                'role'    => 'Mediocentro',
                'photo'   => 'unai.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 6,
                'name'    => 'David',
                'role'    => 'Mediocentro',
                'photo'   => 'player.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 18,
                'name'    => 'Antonio',
                'role'    => 'Mediocentro',
                'photo'   => 'antonio.jpg',
                'minutes' => 60,
                'goals'   => 1,
                'matches' => 1,
            ],
                        [
                'number'  => 77,
                'name'    => 'Nacho',
                'role'    => 'Mediocentro',
                'photo'   => 'nacho.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 80,
                'name'    => 'Bonilla',
                'role'    => 'Mediocentro',
                'photo'   => 'player.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
                        [
                'number'  => 9,
                'name'    => 'Hugo (Sebi)',
                'role'    => 'Delantero',
                'photo'   => 'hugo.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            [
                'number'  => 7,
                'name'    => 'Tom Fox',
                'role'    => 'Delantero',
                'photo'   => 'tom.jpg',
                'minutes' => 30,
                'goals'   => 1,
                'matches' => 1,
            ],
                        [
                'number'  => 95,
                'name'    => 'Juanpe',
                'role'    => 'Delantero',
                'photo'   => 'jp.jpg',
                'minutes' => 0,
                'goals'   => 0,
                'matches' => 0,
            ],
            // ...más jugadores
        ];

        return view('inicio', ['players' => $players]);
    }
}
